import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/Navbar";
import { Toaster } from "react-hot-toast";
import Footer from "@/component/Footer";
import AosProvider from "@/component/AosProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Veedoo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-[#111827] text-gray-100 overflow-x-hidden">
        {/* Wrap everything inside AosProvider */}
        <AosProvider>
          {/* Toaster for success/error notifications */}
          <Toaster position="top-center" />
          
          {/* Navbar */}
          <Navbar />
          
          {/* Main page content */}
          <main className="flex-1 flex flex-col">{children}</main>

          {/* Footer */}
          <Footer />
        </AosProvider>
      </body>
    </html>
  );
}